#1. What are the names of all the countries in the country table?
select country_name
from country;

#2. What is the total number of customers in the customers table?
select count(customer_id) as 'Total Number of Customers'
from customers;

#3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?
select avg(age) as 'Average age of customers who can receive marketing emails'
from customers 
where can_email = 'yes';

#4. How many orders were made by customers aged 30 or older?
select count(order_id)
from orders
join customers 
on customers.customer_id = orders.customer_id 
where customers.age >= 30;

#5. What is the total revenue generated by each product category?
select products.category , sum(products.price)
from products 
join baskets 
on baskets.product_id = products.product_id 
group by products.category ;

#6. What is the average price of products in the 'food' category?
select avg(price) 
from products 
where category = 'food';

#7. How many orders were made in each sales channel (sales_channel column) in the orders table?
select sales_channel, count(order_id)
from orders
group by sales_channel;

#8.What is the date of the latest order made by a customer who can receive marketing emails?
select o.customer_id, max(o.date_shop) 
from orders o 
join customers c 
on c.customer_id = o.customer_id
where c.can_email = 'yes'
group by o.customer_id; 

#9. What is the name of the country with the highest number of orders?
select country_name, count(order_id)
from country c 
join orders o 
on o.country_id = c.country_id
group by country_name
order by count(order_id) desc 
limit 1;

#10. What is the average age of customers who made orders in the 'vitamins' product category? 
select category , avg(age)
from products p 
join baskets b 
on b.product_id = p.product_id
join orders o 
on o.order_id = b.order_id
join customers c 
on c.customer_id = o.customer_id
where category = 'vitamins';


